name: Build & Release
on:
  push:
    branches: [ main ]
  release:
    types: [created]

jobs:
  build:
    name: Build & Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.29.1"
          channel: "stable"
          cache: true

      - name: Ensure Flutter is Installed
        run: flutter doctor

      - name: Get Dependencies
        run: flutter pub get

      - name: Clean Project
        run: flutter clean

      - name: Build Optimized APK
        run: flutter build apk --release --split-per-abi

      - name: Verify APK Exists
        run: ls -l build/app/outputs/flutter-apk/

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apks
          path: build/app/outputs/flutter-apk/*.apk
          retention-days: 7

  release:
    name: Release APK
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download APK Artifact
        uses: actions/download-artifact@v4
        with:
          name: release-apks
          path: build/app/outputs/flutter-apk/

      - name: List Downloaded Files (Debugging)
        run: ls -R build/app/outputs/flutter-apk/

      - name: Delete Previous Release (if exists)
        run: |
          RELEASE_ID=$(gh release view ${{ github.ref_name }} --json id --jq '.id' || echo "")
          if [[ -n "$RELEASE_ID" ]]; then
            gh release delete ${{ github.ref_name }} --yes
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create New GitHub Release (Without Source Code)
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          generate_release_notes: false
          files: build/app/outputs/flutter-apk/*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
